- name: Delete internet gateway in Environment {{ ec2_environment }}
  amazon.aws.ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ item.vpc_id }}"
    state: absent
  loop: '{{ all_vpcs.vpcs }}'
