# Tags are used to uniquely identify route tables within a VPC
# when the route_table_id is not supplied.
- name: Delete Route Table
  amazon.aws.ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ all_vpcs.vpcs[0].vpc_id }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Name: "{{ ec2_resource_prefix }}-route-table"
    state: absent
