- name: Create ELB
  amazon.aws.elb_classic_lb:
    name: "{{ ec2_resource_prefix }}-elb"
    region: "{{ ec2_region }}"
    state: present
    security_group_ids: "{{ create_sg.group_id }}"
    subnets: "{{ create_subnet.subnet.id }}"
    instance_ids: "{{ aws_instances }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: true
    stickiness:
      enabled: false
    tags:
      Environment: "{{ ec2_environment }}"
  register: create_elb

- name: Print ELB DNS Record
  ansible.builtin.debug:
    msg: "ELB DNS: {{ create_elb.elb.dns_name }}"

- name: set fact with elb dns
  ansible.builtin.set_fact:
    elb_dns: "{{ create_elb.elb.dns_name }}"

- name: DNS for ELB
  community.aws.route53:
    state: present
    zone: "{{ dns_zone }}"
    record: "{{ ec2_resource_prefix }}.{{ dns_zone }}"
    type: CNAME
    overwrite: true
    value: "{{ elb_dns }}"
  when: dns_zone is defined and dns_zone != ""
